export const PRODUCT_FETCHs = "PRODUCT_FETCHs";
export const PRODUCT_FETCHs_SUCCESS = "PRODUCT_FETCHs_SUCCESS";
export const PRODUCT_FETCHs_ERROR = "PRODUCT_FETCHs_ERROR";

export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR";

export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";

export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR";

export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";
